Name: Vacalares, Karl Richie B.

# NumPy
NumPy, short for Numerical Python, is a fundamental package for scientific computing in Python. It provides a powerful N-dimensional array object, along with a variety of functions for performing operations on these arrays, including mathematical, logical, shape manipulation, sorting, selecting, and basic linear algebra, among others. With its ability to handle large, multi-dimensional arrays and matrices efficiently, NumPy forms the foundation for many other scientific and data analysis libraries in Python, such as SciPy, Pandas, and machine learning frameworks like TensorFlow. It is widely used in data science, machine learning, and engineering for its performance, ease of use, and extensive community support.

Note that the first ten exercises are in beginner level. While the rest is at a level of above average. By the end of the exercises, you are expected to leverage your knowledge in NumPy.

## 1. Create an Array
Create an Array: Write a program that creates a NumPy array with elements `[1, 2, 3, 4, 5]`. Display the array.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", arr)

## 2. Array Operations
Create two NumPy arrays, `a = [1, 2, 3]` and `b = [4, 5, 6]`. Perform element-wise addition, subtraction, multiplication, and division, and print the results.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b

print("a + b =", addition)
print("a - b =", subtraction)
print("a * b =", multiplication)
print("a / b =", division)

## 3. Array Slicing
Given a NumPy array `arr = [10, 20, 30, 40, 50]`, slice the array to extract the first three elements and the last two elements. Print both slices.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
first_three = arr[:3]

last_two = arr[-2:]
print("First three elements:", first_three)
print("Last two elements:", last_two)

## 4. Create a Matrix
Write a program that creates a 3x3 matrix using NumPy with values from 1 to 9. Display the matrix.

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix:")
print(matrix)

## 5. Matrix Transpose
Create a 2x3 matrix using NumPy, then compute and print its transpose.

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("2x3 Matrix:")
print(matrix)

transpose_matrix = matrix.T
print("\nTranspose:")
print(transpose_matrix)

## 6. Element-wise Operations
Create two 3x3 matrices. Perform element-wise addition, subtraction, and multiplication of these matrices and display the results.

In [ ]:
import numpy as np

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

add_result = matrix1 + matrix2
sub_result = matrix1 - matrix2
mul_result = matrix1 * matrix2

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\n\Addition:")
print(add_result)
print("\n\Subtraction:")
print(sub_result)
print("\nMultiplication:")
print(mul_result)


## 7. Dot Product
Create two vectors (1D arrays) of length 3 using NumPy. Compute and display their dot product.

In [ ]:
# insert your code for `Dot Product`

## 8. Statistical Operations
Given a NumPy array `arr = [4, 8, 15, 16, 23, 42]`, compute and print the mean, median, and standard deviation of the array.

In [ ]:
import numpy as np

arr = np.array([4, 8, 15, 16, 23, 42])

mean_value = np.mean(arr)
median_value = np.median(arr)
std_dev = np.std(arr)

print("Array:", arr)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev)

## 9. Reshape an Array
Create a 1D NumPy array with 12 elements, then reshape it into a 3x4 matrix. Display the reshaped matrix.

In [ ]:
import numpy as np

arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

print("Reshaped 3x4 Matrix:")
print(matrix)

## 10. Conditional Selection
Given a NumPy array `arr = [10, 15, 20, 25, 30, 35]`, use a conditional statement to select and print elements greater than 20.

In [ ]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30, 35])
filtered = arr[arr > 20]

print("Elements greater than 20:", filtered)

## 11. One-hot Encoder
A one-hot encoder is a technique used in machine learning and data preprocessing to convert categorical data into a numerical format that algorithms can work with more effectively. In this process, each unique category (or class) in the categorical feature is represented as a binary vector, where only one element is set to 1 (indicating the presence of that category) and all other elements are set to 0.

For example, consider a categorical feature "Color" with three possible values: "Red," "Green," and "Blue." A one-hot encoder would transform this feature into three binary features:

* "Red" would be encoded as `[1, 0, 0]`
* "Green" would be encoded as `[0, 1, 0]`
* "Blue" would be encoded as `[0, 0, 1]`

In this activity, the assignment of binary values is based on the order of appearance of the class in the given array.

Sample output  1:
```
Enter an array of classes (separated by spaces): dog cat snake horse
[[ 1, 0, 0, 0],
 [ 0, 1, 0, 0],
 [ 0, 0, 1, 0],
 [ 0, 0, 0, 1]]
```

Sample output 2:
```
Enter an array of classes (separated by spaces): dog dog dog cat snake snake horse horse horse cat
[[ 1, 0, 0, 0],
 [ 1, 0, 0, 0],
 [ 1, 0, 0, 0],
 [ 0, 1, 0, 0],
 [ 0, 0, 1, 0],
 [ 0, 0, 1, 0],
 [ 0, 0, 0, 1],
 [ 0, 0, 0, 1],
 [ 0, 0, 0, 1],
 [ 0, 1, 0, 0]]
```

Sample output 3:
```
Enter an array of classes (separated by spaces): lotion lotion mug pencil pencil calendar calendar lotion mug
[[ 1, 0, 0, 0],
 [ 1, 0, 0, 0],
 [ 0, 1, 0, 0],
 [ 0, 0, 1, 0],
 [ 0, 0, 1, 0],
 [ 0, 0, 0, 1],
 [ 0, 0, 0, 1],
 [ 1, 0, 0, 0],
 [ 0, 1, 0, 0]]
```


In [ ]:
classes = input("Enter an array of classes (separated by spaces): ").split()

unique_classes = []
for c in classes:
    if c not in unique_classes:
        unique_classes.append(c)

one_hot = []
for c in classes:
    vector = [1 if c == u else 0 for u in unique_classes]
    one_hot.append(vector)

print(one_hot)


## 12. Convolution Operation
**Task Description**:
Given a 5x5 matrix and a 3x3 kernel, apply the convolution operation manually by sliding the kernel over the matrix. The output will be a 3x3 matrix, where each element is the result of the convolution at that position.

**Convolution Operation**:
The convolution operation involves placing the center of the kernel on a matrix element, multiplying the overlapping values, and summing them up. The kernel is moved across the matrix to compute each element of the resulting matrix. Alternatively, learn the operation from this [YouTube](https://www.youtube.com/watch?v=yb2tPt0QVPY) demo.

Sample Input:
```
Matrix (5x5):
[[20 24 11 12 16]
 [19 17 20 23 15]
 [21 40 25 13 14]
 [ 9 18  8  6 11]
 [31  3  7  9 17]]

Kernel (3x3):
[[1 0 -1]
 [2 0 -2]
 [1 0 -1]]
```

Output:
```
[[ 3 27 16]
 [-8 60 24]
 [22 45 -5]]
```

In [ ]:
import numpy as np

matrix = np.array([
    [20, 24, 11, 12, 16],
    [19, 17, 20, 23, 15],
    [21, 40, 25, 13, 14],
    [ 9, 18,  8,  6, 11],
    [31,  3,  7,  9, 17]
])

kernel = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
])

matrix_size = matrix.shape[0]
kernel_size = kernel.shape[0]
output_size = matrix_size - kernel_size + 1
output = np.zeros((output_size, output_size), dtype=int)

for i in range(output_size):
    for j in range(output_size):
        sub_matrix = matrix[i:i+kernel_size, j:j+kernel_size]
        conv_value = np.sum(sub_matrix * kernel)
        output[i, j] = conv_value

print(output)

# Pandas
Pandas is a powerful and widely-used data manipulation and analysis library in Python, designed to handle structured data with ease and efficiency. Built on top of NumPy, Pandas introduces two primary data structures: Series (one-dimensional labeled arrays) and DataFrame (two-dimensional labeled tables), which allow users to perform a wide range of operations, such as data cleaning, filtering, aggregation, and visualization. With its intuitive and flexible syntax, Pandas simplifies the process of working with large datasets, making it an essential tool for data science, machine learning, and any task involving data analysis in Python.

## 1. Loading Data into a DataFrame
Given a CSV file containing information about rice ([rice.csv](https://drive.google.com/file/d/1MmIKxklM498piI-QIPUuWBzlPtSnsyBf/view?usp=sharing)), load the file into a Pandas DataFrame and display the first 5 rows.

In [ ]:
import pandas as pd

df = pd.read_csv('rice.csv')
print(df.head())

## 2. Basic DataFrame Operations
Using the rice.csv DataFrame, print the column names, data types, and a summary of statistics (mean, min, max, etc.) for each numerical column.

In [ ]:
import pandas as pd

df = pd.read_csv('rice.csv')

print("Column Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nSummary Statistics for Numerical Columns:")
print(df.describe())

## 3. Filtering and Selecting Data
From the rice.csv DataFrame, filter the rows where the rice grain's area is greater than 13480 and select only the "Eccentricity" and "Extent" columns.

In [ ]:
import pandas as pd

df = pd.read_csv('rice.csv')
filtered_df = df[df['Area'] > 13480][['Eccentricity', 'Extent']]

print(filtered_df)

## 4. Handling Missing Data
Given a DataFrame with missing values in some rows, identify the missing data, then drop the rows with missing data.

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, None, 30, 22],
    'Salary': [50000, 60000, None, 45000]
}

df = pd.DataFrame(data)

print("Missing data in each column:")
print(df.isnull())     
print("\nCount of missing values per column:")
print(df.isnull().sum())

df_cleaned = df.dropna()
print("\nDataFrame after dropping rows with missing data:")
print(df_cleaned)

## 5. Grouping and Aggregating Data
Using the `rice.csv` DataFrame, group the data by the `Perimeter` column and calculate the `convex area` for each department.

In [ ]:
import pandas as pd

df = pd.read_csv('rice.csv')
convex_sum = df.groupby('Perimeter')['Convex_Area'].sum()
print("Sum of ConvexArea for each Perimeter:")
print(convex_sum)

convex_mean = df.groupby('Perimeter')['Convex_Area'].mean()
print("\nMean of ConvexArea for each Perimeter:")
print(convex_mean)

## 6. Sorting Data
Sort the rice.csv DataFrame by "Perimeter" in descending order and display the top 5 highest `Area`.

In [ ]:
import pandas as pd

df = pd.read_csv('rice.csv')

sorted_df = df.sort_values(by='Perimeter', ascending=False)
top5_area = sorted_df[['Area', 'Perimeter']].head(5)
print(top5_area)

## 7. Data Visualization with Pandas
Using the rice.csv DataFrame, create a box chart that shows the statistics for  each column. (You may need to use Matplotlib.)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('rice.csv')

plt.figure(figsize=(12, 6))
df.boxplot()
plt.title('Box Plot of Rice Dataset Columns')
plt.ylabel('Values')
plt.xticks(rotation=45) 
plt.show()

---
## End of laboratory exercises. Nothing follows.


## Future addition to problems in numpy
activation functions